package com.brainfreezed.profitlense.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductAnalysisDTO {
    private UUID productId;
    private String productName;
    private String category;
    
    // Pricing data
    private BigDecimal currentPrice;
    private BigDecimal competitorMedian;
    private String pricingSignal;
    private BigDecimal suggestedPrice;
    
    // Advisory Text generated by orchestrator
    private String advisoryText;

    // Forecast data (sorted by date ascending)
    private List<ForecastDTO> forecasts;
}
